on:
  pull_request:
    types: [closed]
    branches:
      - main
      - master
jobs:
  delete_tags:
    if: github.event.pull_request.merged == true &&
      github.event.pull_request.head.ref == 'release' &&
      contains(github.event.pull_request.labels.*.name, 'auto-deploy')
    uses: boromir674/automated-workflows/.github/workflows/go-delete-tags.yml@18b20a331650752492a8ed614feb4057216b6547  # v1.12.0
    secrets:
      # pass in GITHUB PAT with Repo Content RW permission/access
      GH_PAT_CONTENT_RW: ${{ secrets.GH_TOKEN_CONTENT_RW }}
